### ISSUE TITLE
Feature Request:  Add The Feature for Hide/Show Password.

### ISSUE THREAD

**Issue by singhkunal01** [varunKT001/tomper-wear-ecommerce#10]
**Is your feature request related to a problem? Please describe**

hey @varunKT001, what I am thinking is to add the hide/show feature in the password? What do you say? Let me Know.

**Describe the solution you thought**

Without any disturbance of full code, I will just small code for this by adding icons for both the options wherever you provided the feature of entering a password.

**Additional context (if any)**

No That's it about what I'm thinking 

Also, I'm a GSSOC'2022 participant, Let me know If you are okay with it If Yes then please assign this to me.

*Thank You*

**Comment by singhkunal01** [comment]
hey @varunKT001 sorry but i'm in newbie in react for now because i am learning it and this is a little bit bigger project in terms of codebase and yes I'm interested to work on this too but i request you to help me.

Till now i have found the login page and also i know the logic that how can i do this but i don't know that how and in which file i add that toggle feature ?

**Comment by varunKT001** [comment]
Hey @singhkunal01,
You can find the login and register pages at `src/pages/LoginPage/index.js` and `src/pages/RegisterPage/index.js`
And for writing the styles, you can go to the `src/pages/LoginPage/styles.js` and  `src/pages/RegisterPage/styles.js`

You have to implement the toggle feature in both the login and registers pages. Also, the majority of the code (and the styling) in both of them is the same, so you can do some copy-paste too.

You can follow these steps for adding the functionality:
- add a state which contains the boolean values to show or hide the password.
-  dynamically add the `type=password` or `type=text` using the state in the input elements.
- create a toggle button (or, icon) to toggle the value of the state.

Please try to follow the existing code style. Also, for styling, try to implement it such that it blends with the current design and theme.

If you still have any more doubts, we'll soon be having a separate channel in the discord server. You can ping me there 👍

**Comment by singhkunal01** [comment]
- Thank @varunKT001 you but For this first i have to learn some more react so please tell me the time limit to do that so that i can do it accordingly.

- Also don't forgot to add the server link so that i can join ASAP.

**Comment by varunKT001** [comment]
> Thank @varunKT001 you but For this first i have to learn some more react so please tell me the time limit to do that so that I can do it accordingly.

At the moment, I have not decided on any time limit. I'll do it once the discord channel is created and the mentors are allotted. Till then, you can learn and implement it according to your own pace.
But I still recommend not taking much time. It's a small issue, and It won't require much time even if you have to learn in parallel.

I'll ping the contributors active on this project once the channel is set up, so don't worry 👍

**Comment by singhkunal01** [comment]
Okay @varunKT001 thank you so much sir.

**Comment by varunKT001** [comment]
@singhkunal01 Any updates?

**Comment by singhkunal01** [comment]
sorry because of my laptop issues i am able to work now will you please give some more time so that i can ?

**Comment by varunKT001** [comment]
@singhkunal01 Okay, no problem. Try to do it soon 👍

**Comment by Siddhesh777** [comment]
Hey @varunKT001 😅
Can I do this task ?
If yes please assign this task to me

**Comment by varunKT001** [comment]
@Siddhesh777 Currently it's assigned to @singhkunal01 😅 
If he gets un-assigned, I'll assign it to you 👍

**Comment by Siddhesh777** [comment]
fine @varunKT001  😅
I have already implemented the functionality 

![abc](https://user-images.githubusercontent.com/77476772/157020489-9bf4312f-f7c7-4db7-aaa7-4d825239b4ef.png)

if you wish to merge just mention me here😅

**Comment by varunKT001** [comment]
@Siddhesh777 I can't do that right now 😅
As I told you, if I ever un-assign this issue, I'll assign it to you, and then you make a pull request 👍

**Comment by singhkunal01** [comment]
no problem @varunKT001 this guy put his efforts you can merge i have no problem i have some problem in my laptop and may be it would take some time so we can appreciate @Siddhesh777 work .

**Comment by varunKT001** [comment]
Okay, I'll un-assign you then @singhkunal01 

@Siddhesh777 You can work upon it 👍
