### ISSUE TITLE
Bug: Price range is not having a lower limit

### ISSUE THREAD

**Issue by Neha9849** [varunKT001/tomper-wear-ecommerce#14]
**Describe the bug**
I think it will be good if it also has a lower limit in price range while filtering, as users can choose their range according to their budget.
**Steps to reproduce the behavior**

**Expected behavior**
 It will have both lower and upper limit
**Screenshots (if applicable)**

**Additional context (if any)**

**Comment by Neha9849** [comment]
I would like to work on it .
Please assign it to me if you think this is appropriate.

**Comment by varunKT001** [comment]
It's a great idea @Neha9849 👍
Go ahead 🚀

**Comment by varunKT001** [comment]
@Neha9849 Any updates?

**Comment by sagnik2001** [comment]
Hey @varunKT001 , is this issue available??

**Comment by varunKT001** [comment]
Hmm, since she is not responding, you go ahead with the issue @sagnik2001 🚀

**Comment by sagnik2001** [comment]
Hey @varunKT001, what will be the lower limit price a user will be able to have according to you ??

**Comment by varunKT001** [comment]
@sagnik2001 
The least price from all the products will be the lower limit 👍

**Comment by sagnik2001** [comment]
Okay,got it

**Comment by impriyanshu-in** [comment]
hey, @varunKT001 are the issues resolved?

**Comment by varunKT001** [comment]
@impriyanshu-in Yes 😅
