### ISSUE TITLE
Feature Request: Social media icons 

### ISSUE THREAD

**Issue by suman-shah** [varunKT001/tomper-wear-ecommerce#29]
### Is your feature request related to a problem? Please describe.

If we add some attractive social media icons then it will look great 

### Describe the solution you'd like.

I want to take this issue and add social media icons on footer of the page 

### Additional context (if any)

I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by varunKT001** [comment]
Hey @suman-shah 👋
Can put some screenshots of the social media icons you are talking about?

**Comment by suman-shah** [comment]
here are some sample icons for social handles 

![image](https://user-images.githubusercontent.com/61034696/156887973-5fb33545-a353-4b13-8df2-2480b2c8ecf6.png)

**Comment by varunKT001** [comment]
These are the same icons we have now. Also, since the footer is dark, they won't look good as they are looking now 😕
