### ISSUE TITLE
Bug: No check for mobile number in checkout

### ISSUE THREAD

**Issue by Bhavya-Parikh** [varunKT001/tomper-wear-ecommerce#3]
While checking out there is no check if mobile number is 10 digits or not this can be improved. Please assign the task so I can work on it.

**Comment by varunKT001** [comment]
Hey @Bhavya-Parikh 👋 
Since this project was added, at last, mentors' allotment and other stuff are still pending. Also, I'm yet to create the contribution guidelines and a setup guide.
Don't worry, I'll assign this issue to you, once things are on track 👍

PS: From next on, while creating an issue or pull request, make sure to strictly follow the provided templates. You can leave things blank which are not applicable, but just follow the pattern.

**Comment by Bhavya-Parikh** [comment]
Hey!
Okayy! No worries :)

Sure! Actually I am new to open source and dev and I was excited as I found this bug, Sorry for that. Can you please provide a example like how this can be written in template? I am not supposed to delete the other comments in template and leave them blank or correct me if I am wrong

**Comment by varunKT001** [comment]
> I am new to open source and dev and I was excited as I found this bug.

First of all congrats on starting off with your opensource journey. And don't worry, I'll assign this issue to you 👍 

> Can you please provide a example like how this can be written in template?

You don't have to create the template. When you create a new issue or a pull request, you get a default template where you can fill in the details.

> I am not supposed to delete the other comments in template and leave them blank or correct me if I am wrong

You can either delete or leave it blank, no issues. Just follow the pattern 👍

**Comment by varunKT001** [comment]
Hey @Bhavya-Parikh 👋,
Mentors allotment will take some time 😅
I'm assigning you the issue and you can work upon it 👍
Make sure to follow the templates provided while making a PR 👍

**Comment by Krish2208** [comment]
I would like to contribute to this issue under GSSoC22

**Comment by varunKT001** [comment]
Hey @Krish2208 👋,
It's already assigned to @Bhavya-Parikh
If it gets un-assigned, I'll assign it to you 👍

**Comment by varunKT001** [comment]
Any updates @Bhavya-Parikh?
I don't think this bug should have taken much time 🙂
Try to do it fast or I have to un-assign you.

**Comment by Bhavya-Parikh** [comment]
> Any updates @Bhavya-Parikh? I don't think this bug should have taken much time 🙂 Try to do it fast or I have to un-assign you.

Sorry for the delay, Yeah i did fix the bug i feel but when i try to run the project using npm start it is loading a blank page in chrome, I was trying to fix the issue by googling, I reversed the changes i made, cloned the repo again followed all the steps of setup, installed firebase, updated npm but the issue seems to persists I am unable to know why.

I am attaching screenshots of errors from Chrome's console , please help out :( . And sorry if this is something silly [
![te](https://user-images.githubusercontent.com/94140721/156503505-d622b474-50af-4222-9e74-91f835a2ec08.png)
![te1](https://user-images.githubusercontent.com/94140721/156503542-7b635263-fb2f-48fe-8fc7-118650a52a81.png)
](url)

**Comment by varunKT001** [comment]
You have to rename `.env.sample` file to `.env`
This is will fix the issue 👍
