### ISSUE TITLE
Feature Request: Change footer icon colors and apply hover effect on footer links

### ISSUE THREAD

**Issue by varunKT001** [varunKT001/tomper-wear-ecommerce#31]
### Is your feature request related to a problem? Please describe.

Currently, we can see the dark footer background through the icons, which looks odd 😕 

![image](https://user-images.githubusercontent.com/83509023/156888944-07424031-127a-4a07-874b-982a94fff9fe.png)

### Describe the solution you'd like.

- Change the icon color of all footer icons to `var(--clr-primary-5)`
- Change the text color of the footer links and the bottom-most text to `var(--clr-grey-6)`
- Apply hover effect on the footer links: Change text color to `var(--clr-primary-5)` on hover

**Comment by sagnik2001** [comment]
Hey @varunKT001 can you assign me this issue under GSSoc 22'

**Comment by varunKT001** [comment]
@sagnik2001 Go for it 🚀
