### ISSUE TITLE
Feature Request: Add a image magnifier

### ISSUE THREAD

**Issue by jeevanalok** [varunKT001/tomper-wear-ecommerce#34]
### Is your feature request related to a problem? Please describe.

When we hover around the product to get a good look, if the image provided is not big enough then we can't notice the details .

### Describe the solution you'd like.

I want to add a magnifier which would enlarge the image when hovered over providing a clear clarity for the customer.

### Additional context (if any)

Issue is raised under GSSOC'22

**Comment by varunKT001** [comment]
Hey @jeevanalok 👋
There is already an issue regarding this feature.

**Comment by jeevanalok** [comment]
Ok
