### ISSUE TITLE
Feature Request: Make the cards Responsive

### ISSUE THREAD

**Issue by Kumar-laxmi** [varunKT001/tomper-wear-ecommerce#35]
### Is your feature request related to a problem? Please describe.

![image](https://user-images.githubusercontent.com/76027425/156924895-280d4862-934f-4b68-ae09-c6cf0793004f.png)

In above image we can make the cards named - Mission, Vision and History as responsive.

### Describe the solution you'd like.

I will be installing vanilla-tilt.js file and also calling it which has many pre-defined js functions that have many interactive and stunning functions that can convert static card view to a much dynamic card view.

### Additional context (if any)

Not any thing much for now!!!

**Comment by varunKT001** [comment]
Hey @Kumar-laxmi 👋 

The cards are responsive for all screen sizes, you can test them using the dev tools.

Also, can you share some examples of what type of dynamic card view you are talking about?

**Comment by Kumar-laxmi** [comment]
https://micku7zu.github.io/vanilla-tilt.js/ 

Have a look at the above website

**Comment by Kumar-laxmi** [comment]
The cards could be made dynamic in the ways shown in the website

**Comment by varunKT001** [comment]
@Kumar-laxmi No doubt that the cards look stunning, but don't you think it would an overkill if we use those effects for simple cards that we have?

If you want to implement that, you can go ahead. But I can't guarantee that your change will get merged. To get merged, it should look good on TomperWear. If they didn't look good or didn't blend well with the overall website, I won't merge that.

So, do you want to work on it?

**Comment by Kumar-laxmi** [comment]
Look I won't give a tilt effect but a little of zooming effect when we hover our mouse over it.

**Comment by Kumar-laxmi** [comment]
Look initally it make look weird but if we slowly apply to all in other way around, it will look good

**Comment by Kumar-laxmi** [comment]
More over the website itself is based on ecommerce and as far as I know, ecommerce website mostly have these stunning effects to draw our attention on

**Comment by Kumar-laxmi** [comment]
I can only work if you want or else I can close this issue

**Comment by varunKT001** [comment]
Okay, you can go ahead with that 🚀 
But to get your change get merged, it should look good 👍

**Comment by Kumar-laxmi** [comment]
yeah obviously

**Comment by Kumar-laxmi** [comment]
thanks

**Comment by varunKT001** [comment]
You can start working on this 👍

**Comment by varunKT001** [comment]
@Kumar-laxmi
I don't think you are still working on it, It's 24 days 🙂

**Comment by Kumar-laxmi** [comment]
Oh My God I totally missed it, I will do by today night.

Really sorry for that

**Comment by varunKT001** [comment]
@Kumar-laxmi Okay 👍
