### ISSUE TITLE
Bug: Logging in should be required before filling the cart

### ISSUE THREAD

**Issue by Siddhesh777** [varunKT001/tomper-wear-ecommerce#43]
### What happened?

I think before starting feeling the cart, the user must log in.
Because it can happen that some user just surfed the website and added items to the cart but didn't purchase/log in.
Then when another person will log in, then those previous items will get added to his cart.

### How can we reproduce this bug?

We can keep a button of login in /cart if user isn't logged in
![7](https://user-images.githubusercontent.com/77476772/158325315-45490daa-a4c7-4bfb-bd55-01357d8600dd.png)

### Additional context (if any)

I am contributor at gssoc'22
Please assign this task to me

**Comment by varunKT001** [comment]
@Siddhesh777 
If you visit some other e-commerce platforms, you can see that they allow you to fill your cart even if you are not logged in. Also, the cart data is stored in `LocalStorage` and doesn't require any API call to the TomperWear Server, it won't create any problem even if we allow users to add to the cart without logging in 👍 

So I don't think there is an issue with this 😕

**Comment by Siddhesh777** [comment]
yeah alright @varunKT001 👍🏻
