### ISSUE TITLE
Authentication with Email 

### ISSUE THREAD

**Issue by yogitasaini** [varunKT001/tomper-wear-ecommerce#5]
Please assign this task to me

**Comment by yogitasaini** [comment]
I just want to add  sign in with email feature for user convenience using firebase

**Comment by varunKT001** [comment]
Hey @yogitasaini 👋,
Actually, this is done on purpose. Everyone is not comfortable using a real Email while testing out projects. If you add email verification, people would need to add their real email addresses. 
So, I'm sorry, we can't add this feature. Hope you got my point 😅.

PS:
From next on, while creating an issue or pull request, make sure to strictly follow the provided templates. You can leave things blank which are not applicable, but just follow the pattern.
