### ISSUE TITLE
Feature Request: Toggle Password visibility while changing the password.

### ISSUE THREAD

**Issue by Siddhesh777** [varunKT001/tomper-wear-ecommerce#50]
### Is your feature request related to a problem? Please describe.

It is necessary for the user to know what password he/she has entered.
For this, there must be a button which toggles its visibility.

![1](https://user-images.githubusercontent.com/77476772/159118635-081ce47d-5067-405c-a895-23688a4906ee.png)

### Describe the solution you'd like.

We can use react hook useState for implementing this functionality.

### Additional context (if any)

I am contributor at gssoc'22.
Please assign this issue to me.

**Comment by varunKT001** [comment]
@Siddhesh777 Go ahead 👍
