### ISSUE TITLE
Title: Responsiveness issue on Home/ Cart page

### ISSUE THREAD

**Issue by Prikshit-anthal** [varunKT001/tomper-wear-ecommerce#53]
### Describe your issue.

Delete button getting out of screen width when an item is added to cart.

### Screenshots (if applicable).

![Screenshot from 2022-03-30 15-01-28](https://user-images.githubusercontent.com/79476164/160800252-b8f24c80-0ace-41a5-8c5a-bfad4c3476bb.png)

### Additional context (if any)

Decreasing Font size for small screen size will fix this issue.

**Comment by Prikshit-anthal** [comment]
I'm GSSOC'22 participant, kindly assign me this issue.

**Comment by varunKT001** [comment]
Hi @Prikshit-anthal

I didn't notice that at first. Well, I'm glad you found it 😅 

You can work upon it 🚀
