### ISSUE TITLE
Bug: When nav-bar is opened in small screen, user can still scroll down the homepage hidden behind navbar. 

### ISSUE THREAD

**Issue by Prikshit-anthal** [varunKT001/tomper-wear-ecommerce#54]
### What happened?

I opened nav-bar in my mobile, but was able to scroll down homepage directly from opened nav-bar.

### How can we reproduce this bug?

Open this project on your mobile. At homepage open nav-bar, then try scrolling. Close nav-bar you will notice homepage has scrolled down.

![Screenshot from 2022-03-30 15-05-47](https://user-images.githubusercontent.com/79476164/160801212-d112cbdc-66e1-43c8-b47d-871d4e01eb42.png)

In this screenshot you can see scrollbar at right of navbar being scrolled down.

### Urgency (Optional)

Medium priority

**Comment by Prikshit-anthal** [comment]
I'm GSSOC'22 participant. Kindly,assign this issue to me.

**Comment by varunKT001** [comment]
Hi @Prikshit-anthal 

Yeah, that's a bug, which I didn't notice at first 😅 

You already have issue #53 assigned to you. I'm assigning you this one also, but make a separate pull requests for both the issues 👍

**Comment by Prikshit-anthal** [comment]
@varunKT001 I just wanted to know if you are storing user cart data on backend or not? Because mine is not storing.

**Comment by varunKT001** [comment]
@Prikshit-anthal 
Cart data is stored in the LocalStorage in your browser. After you logout, the cart is cleared 😅

**Comment by Prikshit-anthal** [comment]
Are you ok with firebase as backend, as you have used firebase Auth too. I am well versed in firebase i can contribute in it.

**Comment by varunKT001** [comment]
@Prikshit-anthal 
NO
Keep that as it is. Firebase is just for the auth purpose so that we don't have to do all that on the backend. If you want to contribute to the Backend, you can go to the backend repository of TomperWear 👍
