### ISSUE TITLE
Backend Routes and Models.

### ISSUE THREAD

**Issue by ayush25102001** [varunKT001/tomper-wear-ecommerce#56]
### Describe your issue.

I will create a userModel according to the details in the signUp form for now later more fields can be added, accordingly the entries will be added to the user colletion.
Then I will also create login and register API endpoints at the backend where I will also connect to the database(locally for now). 
I wish to work with the backend part.

Participant under Gssoc'22.

**Comment by varunKT001** [comment]
@ayush25102001 
The authentication part for the frontend is handled by firebase, so no need for custom authentication.
