### ISSUE TITLE
Feature Request: Loading spinner when button is disabled

### ISSUE THREAD

**Issue by varunKT001** [varunKT001/tomper-wear-ecommerce#6]
**Is your feature request related to a problem? Please describe.**
Currently while loading, the then is disabled and its opacity is reduced:
![image](https://user-images.githubusercontent.com/83509023/156176989-7989da37-ad0f-49e0-8bda-895104d2a4e7.png)
Change it to something like this when loading:
![image](https://user-images.githubusercontent.com/83509023/156177140-ebb248b0-e791-498d-a68c-d017fea95941.png)

**Describe the solution you thought**
You may opt for any solution you are comfortable with. Just make sure that whatever you implement is maintainable and does not break any existing functionality.
My suggestion would be to create a global button component accepting all the required props and make a check inside the button if the loading state is true. 

**Additional context (if any)**
- Make sure you don't change anything for the `src/components/StripeCheckout` component for this issue.
- You can use the following resource for getting an animated loader SVG: [loading.io](https://loading.io/)

**Comment by Abhinav0909** [comment]
@varunKT001 Hey,I have checked your isssue.So can you assign it to me

**Comment by sagnik2001** [comment]
Can I work this issue under GsSoc 22

**Comment by sulogna2001** [comment]
Hey Can you assign this issue under GSSOC22

**Comment by varunKT001** [comment]
**Guys note that the issues will be given on a first come first serve basis.**

@Abhinav0909 is the first to claim the issue, so I'm gonna assign it to him 🚀 

@sagnik2001 and @sulogna2001, I'll be creating more issues so stay tuned 🎉
Till then, you can also create some issues if you find something you can improve in TomperWear 😄

I'll also be creating a GitHub workflow to automatically assign the issues so you guys don't have to wait for assignment 👍

**Comment by varunKT001** [comment]
@Abhinav0909 Make sure you read the [contribution guidelines](https://github.com/varunKT001/tomper-wear-ecommerce/blob/main/CONTRIBUTING.md) before contributing. Also, while making a pull request, make sure to strictly follow the provided pull request template 👍

**Comment by varunKT001** [comment]
@Abhinav0909 Any updates on this?

**Comment by varunKT001** [comment]
@sagnik2001 sure 👍

**Comment by Abhinav0909** [comment]
ok ,I will complete this issue by tommorow

**Comment by varunKT001** [comment]
@Abhinav0909 Great 👍

**Comment by Abhinav0909** [comment]
hey sorry for the delay can i deliver the issue by tommorow evening.I am working on it.There is a network issue here.Again sorry for delay

**Comment by Abhinav0909** [comment]
Right now I can't do npm start.The answer to that problem statement is to delete node modules which is given to me.

**Comment by varunKT001** [comment]
> hey sorry for the delay can i deliver the issue by tommorow evening.I am working on it.There is a network issue here.Again sorry for delay

Sure, take your time 👍

**Comment by varunKT001** [comment]
> Right now I can't do npm start.The answer to that problem statement is to delete node modules which is given to me.

Okay, try that. If still there is problem, you can ping me on TomperWear discord channel, I'll look into that 👍

**Comment by Abhinav0909** [comment]
could you provide me with discord server link so that I can talk to you

**Comment by varunKT001** [comment]
You are a participant of GSSoC'22 right?

**Comment by Abhinav0909** [comment]
yes

**Comment by varunKT001** [comment]
Then you should have got the discord invitation link in your selection mail.

**Comment by Abhinav0909** [comment]
ok,

**Comment by Abhinav0909** [comment]
I have joined discord but is there any specific voice channels made for you or where can I have talk with you.It is a little bit confusing since it's first time experience.I couldn't figure out .

**Comment by varunKT001** [comment]
You can go to the self-rules channel, and on scrolling down, you'll find TomperWear role. React on it to unlock the TomperWear channel.

**Comment by varunKT001** [comment]
It's already 5 days @Abhinav0909 🙁 
What's the status?

**Comment by Abhinav0909** [comment]
Yeah but npm start is not happening because of comparability issues of react scripts

**Comment by Abhinav0909** [comment]
Yeah but npm start is not happening because of comparability issues of react scripts

**Comment by varunKT001** [comment]
It's working fine for me and all other contributors 🙁
I think that's an issue from your side. I assume that you won't be able to complete this soon, so I'm re-assigning the issue 👍

@sagnik2001 You want to work on this?

**Comment by Abhinav0909** [comment]
Hmm ok

**Comment by sagnik2001** [comment]
hey @varunKT001 you can assign this issue to me

**Comment by varunKT001** [comment]
Okay, assigned to you @sagnik2001 🚀

**Comment by sagnik2001** [comment]
Should I implement this feature only for login button or every button makes a request to the api

**Comment by varunKT001** [comment]
> Should I implement this feature only for login button or every button makes a request to the API

All the buttons 👍

**Comment by sagnik2001** [comment]
Hey @varunKT001, while implementing a loading spinner what I found is that you used the same state loader for every field which on changing makes a loader in every button so should I make a separate loading state, or is this ok??
![Screenshot from 2022-03-06 20-19-41](https://user-images.githubusercontent.com/74464019/156928884-26b94e69-0572-41f4-a411-26cc85b70096.png)

**Comment by varunKT001** [comment]
@sagnik2001 It's fine, you can leave it like that 👍
