### ISSUE TITLE
Feature Request: Create a better footer

### ISSUE THREAD

**Issue by varunKT001** [varunKT001/tomper-wear-ecommerce#8]
### Is your feature request related to a problem? Please describe
The current footer is pretty basic:

![image](https://user-images.githubusercontent.com/83509023/156216623-a77c9b4c-b830-4d51-9301-c5dfa6c0064f.png)

Create a new footer strictly following the design provided.

**You have to follow this design:**

![Footer](https://user-images.githubusercontent.com/83509023/156213403-4efa4331-8f9b-41bb-a091-a531ec7a9a32.png)

**Use the following color variables:**

|                       | **css-variable** 	|
|----------------|---------------------|
| Background 	| --clr-black      	|
| Grey text  	| --clr-grey-7     	|
| Brown text 	| --clr-primary-5  	|

These CSS variables are defined in the `src/index.css` file. You can use these variables in the components.

**Social media icons:**
You have to use [react-icons](https://react-icons.github.io/react-icons/) for the social media icons. 

### Describe the solution you thought
You may add all the code in the same file, but that would be difficult to maintain.

My suggestions:
1. Add the data for the social media and the links in the `src/utils/contants.js` file. You can get an idea about what to do by looking at some already added data in the file.
3. Import the values and use them inside the component.

### Additional context (if any)
Please make sure that the footer is responsive for all screen sizes

**Comment by Shubham29012001** [comment]
Hey @varunKT001, I would like to work on this issue for GSoC'22.

**Comment by sagnik2001** [comment]
Hey @varunKT001  can I work on this issue under GSSOc 22

**Comment by varunKT001** [comment]
@Shubham29012001 Go ahead 🚀

@sagnik2001 I'll be creating more issues so stay tuned 🎉
Till then, you can also create some issues if you find something you can improve in TomperWear 😄

**Comment by varunKT001** [comment]
@Shubham29012001 Any updates on this?
I don't think this should take much time. Try to complete it soon, or I'll need to re-assign it to someone else 😕

**Comment by Shubham29012001** [comment]
Hey @varunKT001, sorry for the delay. I am working on it. It will be ready by tomorrow. Sorry for the delay.

**Comment by varunKT001** [comment]
@Shubham29012001 Great,
If you are actively working on it, there is no problem, you can take your time. I was just making sure that you are not inactive 😅

**Comment by Sameeksha7464** [comment]
hey @varunKT001 can I work on this issue?
I'm looking for good first issues as I'm a beginner

**Comment by varunKT001** [comment]
Hey @Sameeksha7464 👋,
This issue is already assigned. I'll create some new issues soon, you can look into them. Also, if you find something which could be improved in TomperWear, you can create an issue and work upon it 👍

**Comment by Shubham29012001** [comment]
Hey @varunKT001, will the below footer work? I am facing an issue while selecting the icons from react-icons.

![image](https://user-images.githubusercontent.com/59647563/156808224-d99c04ee-77aa-4403-b517-9ccdfd7db1a9.png)

**Comment by varunKT001** [comment]
> I am facing an issue while selecting the icons from react-icons.

What issues?

Since the whole project uses react-icons only, I don't think there would be any issue while using it 😕

But still you are facing some issues, you can ping me in TomperWear discord channel and we'll discuss it there 👍
